[project]
name = "fsrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bitsandbytes>=0.46.1",
    "jupyter>=1.1.1",
    "nnsight>=0.4.6",
    "sae-lens>=5.10.5",
    "torch>=2.7.0",
    "transformer-lens>=2.15.4",
    "transformers>=4.52.4",
    "trl>=0.15.2",
]
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
