[project]
name = "fsrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "nnsight>=0.4.6",
    "sae-lens>=5.10.5",
    "torch>=2.7.0",
    "transformers>=4.52.4",
]
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"