# Training Configuration
output_dir: "logs/training_run"
num_train_epochs: 1
learning_rate: 1e-4

# Batch size configuration
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
dataloader_num_workers: 8
dataloader_pin_memory: true

# Training optimizations
bf16: true
optim: "adamw_torch_fused"
logging_steps: 10
torch_compile: false

# Additional training parameters
save_steps: 10000
save_total_limit: 2
do_eval: false
load_best_model_at_end: false
