# Main training configuration (Run on appropriate hardware (40GB+ GPU))
defaults:
  - architecture: gemma2_2B
  - training: gemma2_2B
  - wandb: gemma2_2B
  - _self_

# Model saving configuration
models_dir: "models/Gemma2_2B-layer-sweep"

# Override any settings here if needed
hydra:
  run:
    dir: logs/hydra_runs/${now:%Y-%m-%d_%H-%M-%S}
