# Architecture Configuration for full Gemma2-2B training (no SAE)
use_sae: false

model:
  name: "gemma-2-2b-it" # Name on transformer_lens
  device: "cuda"
  dtype: "bfloat16"

# SAE config still present but not used when use_sae is false
sae:
  release: "gemma-scope-2b-pt-res"
  sae_id: "layer_12/width_16k/average_l0_22"
  activation_type: "soft_threshold"  # Options: "soft_threshold", "jump_relu", "relu"
  initial_threshold: 0.01
  bandwidth: 0.001
  dtype: "bfloat16"

dataset:
  name: "princeton-nlp/llama3-ultrafeedback-armorm"
  train_split: "train"
  eval_split: "test"
  sample_size: null  # Set to a number to limit dataset size for testing
  dataset_num_proc: 20
  chat_template: "{{ bos_token }}{% if messages[0]['role'] == 'system' %}{% set system_message = messages[0]['content'] | trim + '\n\n' %}{% set messages = messages[1:] %}{% else %}{% set system_message = '' %}{% endif %}{% for message in messages %}{% if loop.index0 == 0 %}{% set content = system_message + message['content'] %}{% else %}{% set content = message['content'] %}{% endif %}{% if (message['role'] == 'assistant') %}{% set role = 'model' %}{% else %}{% set role = message['role'] %}{% endif %}{{ '<start_of_turn>' + role + '\n' + content | trim + '<end_of_turn>\n' }}{% endfor %}{% if add_generation_prompt %}{{'<start_of_turn>model\n'}}{% endif %}"
